package com.rtcomm.app.ui.admin

import com.rtcomm.app.ui.theme.Space
import com.rtcomm.app.R

import androidx.compose.ui.res.stringResource
import androidx.compose.material3.OutlinedTextField
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.input.PasswordVisualTransformation

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.horizontalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.automirrored.filled.Logout
import androidx.compose.material.icons.filled.Block
import androidx.compose.material.icons.filled.CardGiftcard
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Forum
import androidx.compose.material.icons.filled.Group
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material.icons.filled.Person
import androidx.compose.material.icons.filled.Restore
import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.filled.SmartToy
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.rtcomm.app.data.AdminStats
import com.rtcomm.app.data.AdminUser
import com.rtcomm.app.data.Api
import com.rtcomm.app.data.AppState
import com.rtcomm.app.data.InviteCode
import com.rtcomm.app.data.InviteStats
import com.rtcomm.app.ui.common.ActionSheet
import com.rtcomm.app.ui.common.AppAlertDialog
import com.rtcomm.app.ui.common.AppTopBar
import com.rtcomm.app.ui.common.ConfirmDialog
import com.rtcomm.app.ui.common.ErrorBanner
import com.rtcomm.app.ui.common.FadeSwap
import com.rtcomm.app.ui.common.Format
import com.rtcomm.app.ui.common.InitialsAvatar
import com.rtcomm.app.ui.common.LoadingBox
import com.rtcomm.app.ui.common.EmptyState
import com.rtcomm.app.ui.common.Reveal
import com.rtcomm.app.ui.common.SheetAction
import com.rtcomm.app.ui.common.motionPress
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

/** List<String> 的 Saver：让刚生成的邀请码/兑换码在进程被回收重建后仍然可见。 */
private val StringListSaver = androidx.compose.runtime.saveable.listSaver<List<String>, String>(
    save = { it },
    restore = { it },
)

/** 等待二次确认的破坏性操作。 */
private data class PendingConfirm(
    val title: String,
    val message: String,
    val confirmText: String,
    val action: () -> Unit,
)

/** 一次刷新拉取的全部管理数据。 */
private data class AdminData(
    val stats: AdminStats,
    val users: List<AdminUser>,
    val invites: com.rtcomm.app.data.InviteCodesResp,
    val conversations: List<com.rtcomm.app.data.AdminConversation>,
)

/**
 * 管理后台：账号总览 + 邀请码管理。
 *
 * 入口在设置页仅对管理员可见，但真正的权限判定在服务端
 * （管理接口全部挂了 adminRequired），这里隐藏只是体验优化。
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AdminScreen(onBack: () -> Unit) {
    val scope = rememberCoroutineScope()
    val clipboard = LocalClipboardManager.current
    val snackbar = remember { SnackbarHostState() }

    var tab by remember { mutableIntStateOf(0) } // 0=账号 1=邀请码 2=会话
    var loading by remember { mutableStateOf(true) }
    var err by remember { mutableStateOf<String?>(null) }
    var stats by remember { mutableStateOf(AdminStats()) }
    var users by remember { mutableStateOf<List<AdminUser>>(emptyList()) }
    var invites by remember { mutableStateOf<List<InviteCode>>(emptyList()) }
    var inviteStats by remember { mutableStateOf(InviteStats()) }
    var typeFilter by remember { mutableStateOf("all") }
    var query by rememberSaveable { mutableStateOf("") }
    var showGenerate by remember { mutableStateOf(false) }
    var generating by remember { mutableStateOf(false) }
    var genCount by remember { mutableStateOf("1") }
    var genNote by remember { mutableStateOf("") }
    var lastGenerated by rememberSaveable(stateSaver = StringListSaver) { mutableStateOf<List<String>>(emptyList()) }
    /** 正在操作的目标账号（弹出管理动作菜单） */
    var userActionTarget by remember { mutableStateOf<AdminUser?>(null) }
    var pwdTarget by remember { mutableStateOf<AdminUser?>(null) }
    var conversations by remember { mutableStateOf<List<com.rtcomm.app.data.AdminConversation>>(emptyList()) }
    var convDetail by remember { mutableStateOf<com.rtcomm.app.data.AdminConversation?>(null) }
    var busyAction by remember { mutableStateOf(false) }
    /** 待确认的破坏性操作（作废邀请码 / 禁用账号 / 踢下线 / 清除 Key / 作废兑换码）。 */
    var confirmAction by remember { mutableStateOf<PendingConfirm?>(null) }

    suspend fun reload() {
        loading = true
        err = null
        val res = withContext(Dispatchers.IO) {
            runCatching {
                val s = Api.adminStats()
                val u = Api.adminUsers(typeFilter, query.ifBlank { null })
                val inv = Api.listInvites()
                val convs = Api.adminConversations()
                AdminData(s, u, inv, convs)
            }
        }
        res.onSuccess { d ->
            stats = d.stats
            users = d.users
            invites = d.invites.codes
            inviteStats = d.invites.stats
            conversations = d.conversations
        }
        res.onFailure { err = Api.userMessage(it) }
        loading = false
    }

    LaunchedEffect(Unit) { reload() }

    Scaffold(
        topBar = {
            AppTopBar(
                title = "管理后台",
                onBack = onBack,
            )
        },
        snackbarHost = { SnackbarHost(snackbar) },
    ) { pad ->
        Column(Modifier.fillMaxSize().padding(pad)) {
            TabRow(selectedTabIndex = tab) {
                Tab(selected = tab == 0, onClick = { tab = 0 }, text = { Text("账号") })
                Tab(selected = tab == 1, onClick = { tab = 1 }, text = { Text("邀请码") })
                Tab(selected = tab == 2, onClick = { tab = 2 }, text = { Text("会话") })
                Tab(selected = tab == 3, onClick = { tab = 3 }, text = { Text("AI 设置") })
                Tab(selected = tab == 4, onClick = { tab = 4 }, text = { Text("额度") })
            }
            err?.let { ErrorBanner(it, onRetry = { scope.launch { reload() } }) }

            // 加载状态用一条细进度线表示：不遮内容、不跳版，切页签/搜索时也能立刻看到反馈。
            Box(Modifier.fillMaxWidth().height(4.dp)) {
                Reveal(loading) {
                    LinearProgressIndicator(
                        modifier = Modifier.fillMaxWidth().height(3.dp),
                    )
                }
            }

            // 页签内容之间淡切，替代整块硬替换。
            // 注意：Crossfade 的内容放在同一个 Box 中，同一分支内多个同级组件会叠放；
            // 「账号」页签必须用 Column 包裹，否则统计行/搜索框/列表会互相遮挡。
            FadeSwap(target = tab, modifier = Modifier.fillMaxSize()) { currentTab ->
            when (currentTab) {
                0 -> Column(Modifier.fillMaxSize()) {
                StatsRow(stats)
                // 类型筛选
                Row(
                    Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()).padding(horizontal = 12.dp),
                    horizontalArrangement = Arrangement.spacedBy(Space.sm),
                ) {
                    listOf("all" to "全部", "human" to "用户", "bot" to "机器人").forEach { (key, label) ->
                        FilterChip(
                            selected = typeFilter == key,
                            onClick = { typeFilter = key; scope.launch { reload() } },
                            label = { Text(label) },
                        )
                    }
                }
                Row(
                    Modifier.fillMaxWidth().padding(horizontal = 12.dp, vertical = 6.dp),
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    OutlinedTextField(
                        value = query,
                        onValueChange = { query = it },
                        label = { Text("搜索用户名或昵称") },
                        singleLine = true,
                        keyboardOptions = KeyboardOptions(imeAction = ImeAction.Search),
                        keyboardActions = KeyboardActions(onSearch = { scope.launch { reload() } }),
                        trailingIcon = if (query.isNotBlank()) {
                            {
                                IconButton(onClick = { query = ""; scope.launch { reload() } }) {
                                    Icon(Icons.Filled.Close, contentDescription = "清空搜索")
                                }
                            }
                        } else null,
                        modifier = Modifier.weight(1f),
                    )
                    Spacer(Modifier.width(Space.sm))
                    Button(onClick = { scope.launch { reload() } }) { Text("查询") }
                }

                FadeSwap(if (loading && users.isEmpty()) 0 else if (users.isEmpty()) 1 else 2) { st ->
                    when (st) {
                        0 -> LoadingBox()
                        1 -> EmptyState(Icons.Filled.Search, "没有匹配的账号", "换个关键词或筛选条件试试")
                        else -> LazyColumn(Modifier.fillMaxSize()) {
                            items(users, key = { it.id }) { u ->
                                AdminUserRow(u, Modifier.animateItem()) { userActionTarget = u }
                            }
                        }
                    }
                }
            }
                2 -> {
                FadeSwap(if (loading && conversations.isEmpty()) 0 else if (conversations.isEmpty()) 1 else 2) { st ->
                    when (st) {
                        0 -> LoadingBox()
                        1 -> EmptyState(Icons.Filled.Forum, "还没有会话", null)
                        else -> LazyColumn(Modifier.fillMaxSize()) {
                            items(conversations, key = { it.id }) { c ->
                                AdminConversationRow(c, Modifier.animateItem()) { convDetail = c }
                            }
                        }
                    }
                }
            }
                1 -> {
                InviteTab(
                    stats = inviteStats,
                    invites = invites,
                    onGenerate = { showGenerate = true },
                    onCopy = { code ->
                        clipboard.setText(AnnotatedString(code))
                        scope.launch { snackbar.showSnackbar("已复制邀请码") }
                    },
                    onRevoke = { code ->
                        confirmAction = PendingConfirm(
                            title = "作废邀请码",
                            message = "作废后「$code」将无法再被使用，且不可撤销。",
                            confirmText = "作废",
                        ) {
                            scope.launch {
                                val r = withContext(Dispatchers.IO) { runCatching { Api.revokeInvite(code) } }
                                r.onSuccess {
                                    snackbar.showSnackbar("已作废")
                                    reload()
                                }.onFailure { snackbar.showSnackbar(Api.userMessage(it)) }
                            }
                        }
                    },
                )
            }
                3 -> {
                AiSettingsTab(snackbar = snackbar)
            }
                else -> {
                RedeemCodesTab(snackbar = snackbar, clipboard = clipboard)
            }
            }
            }
        }
    }

    // 账号管理动作
    userActionTarget?.let { target ->
        UserActionDialog(
            user = target,
            onDismiss = { userActionTarget = null },
            onToggleDisabled = {
                val enabling = target.isDisabled
                if (enabling) {
                    busyAction = true
                    scope.launch {
                        val r = withContext(Dispatchers.IO) {
                            runCatching { Api.adminSetUserDisabled(target.id, false) }
                        }
                        busyAction = false
                        r.onSuccess {
                            snackbar.showSnackbar("已恢复 ${target.displayName}")
                            userActionTarget = null
                            reload()
                        }.onFailure { snackbar.showSnackbar(Api.userMessage(it)) }
                    }
                } else {
                    userActionTarget = null
                    confirmAction = PendingConfirm(
                        title = "禁用账号",
                        message = "禁用后「${target.displayName}」将无法登录，此操作会立即生效。",
                        confirmText = "禁用",
                    ) {
                        busyAction = true
                        scope.launch {
                            val r = withContext(Dispatchers.IO) {
                                runCatching { Api.adminSetUserDisabled(target.id, true) }
                            }
                            busyAction = false
                            r.onSuccess {
                                snackbar.showSnackbar("已禁用 ${target.displayName}")
                                reload()
                            }.onFailure { snackbar.showSnackbar(Api.userMessage(it)) }
                        }
                    }
                }
            },
            onResetPassword = { pwdTarget = target; userActionTarget = null },
            onKick = {
                userActionTarget = null
                confirmAction = PendingConfirm(
                    title = "踢下线",
                    message = "「${target.displayName}」的当前登录会立即失效，需要重新登录。",
                    confirmText = "踢下线",
                ) {
                    busyAction = true
                    scope.launch {
                        val r = withContext(Dispatchers.IO) { runCatching { Api.adminKickUser(target.id) } }
                        busyAction = false
                        r.onSuccess {
                            snackbar.showSnackbar("已踢下线，该账号需重新登录")
                            reload()
                        }.onFailure { snackbar.showSnackbar(Api.userMessage(it)) }
                    }
                }
            },
        )
    }

    confirmAction?.let { c ->
        ConfirmDialog(
            title = c.title,
            message = c.message,
            confirmText = c.confirmText,
            onConfirm = c.action,
            onDismiss = { confirmAction = null },
        )
    }

    pwdTarget?.let { target ->
        ResetPasswordDialog(
            user = target,
            busy = busyAction,
            onDismiss = { pwdTarget = null },
            onConfirm = { newPwd ->
                busyAction = true
                scope.launch {
                    val r = withContext(Dispatchers.IO) {
                        runCatching { Api.adminResetPassword(target.id, newPwd) }
                    }
                    busyAction = false
                    r.onSuccess {
                        snackbar.showSnackbar("已重置 ${target.displayName} 的密码")
                        pwdTarget = null
                        reload()
                    }.onFailure { snackbar.showSnackbar(Api.userMessage(it)) }
                }
            },
        )
    }

    // 查看会话（只读）
    convDetail?.let { c ->
        ConversationViewerDialog(conversation = c, onDismiss = { convDetail = null })
    }

    if (showGenerate) {
        AppAlertDialog(
            onDismissRequest = { if (!generating) showGenerate = false },
            title = { Text("生成邀请码") },
            text = {
                Column {
                    Text("邀请码一码一用，仅可用于注册普通账号。", style = MaterialTheme.typography.bodySmall)
                    Spacer(Modifier.height(Space.md))
                    OutlinedTextField(
                        value = genCount,
                        onValueChange = { genCount = it.filter { c -> c.isDigit() }.take(2) },
                        label = { Text("数量（1-50）") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth(),
                    )
                    Spacer(Modifier.height(Space.sm))
                    OutlinedTextField(
                        value = genNote,
                        onValueChange = { genNote = it },
                        label = { Text("备注（可选，便于追溯）") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth(),
                    )
                    Reveal(lastGenerated.isNotEmpty()) {
                        if (lastGenerated.isNotEmpty()) {
                            Spacer(Modifier.height(Space.md))
                            Text("刚生成：", style = MaterialTheme.typography.labelMedium)
                            lastGenerated.forEach { c ->
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Text(c, fontFamily = FontFamily.Monospace, style = MaterialTheme.typography.bodyMedium)
                                    Spacer(Modifier.weight(1f))
                                    TextButton(onClick = {
                                        clipboard.setText(AnnotatedString(c))
                                        scope.launch { snackbar.showSnackbar("已复制") }
                                    }) { Text(stringResource(R.string.action_copy)) }
                                }
                            }
                        }
                    }
                }
            },
            confirmButton = {
                TextButton(
                    onClick = {
                        val n = genCount.toIntOrNull()?.coerceIn(1, 50) ?: 1
                        generating = true
                        scope.launch {
                            val r = withContext(Dispatchers.IO) {
                                runCatching { Api.createInvites(n, genNote.ifBlank { null }) }
                            }
                            generating = false
                            r.onSuccess { resp ->
                                lastGenerated = resp.codes.map { it.code }
                                // 一次就把全部码复制走，方便直接发给人。
                                clipboard.setText(AnnotatedString(lastGenerated.joinToString("\n")))
                                snackbar.showSnackbar("已生成 ${lastGenerated.size} 个并复制")
                                reload()
                            }.onFailure { snackbar.showSnackbar(Api.userMessage(it)) }
                        }
                    },
                    enabled = !generating,
                ) { Text(if (generating) "生成中…" else "生成") }
            },
            dismissButton = { TextButton(onClick = { showGenerate = false; lastGenerated = emptyList() }) { Text(stringResource(R.string.action_close)) } },
        )
    }
}

@Composable
private fun StatsRow(stats: AdminStats) {
    Column(Modifier.padding(horizontal = 12.dp, vertical = 8.dp)) {
        Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(Space.sm)) {
            StatChip("用户", stats.users, Icons.Filled.Person)
            StatChip("机器人", stats.bots, Icons.Filled.SmartToy)
            StatChip(stringResource(R.string.status_online), stats.online, Icons.Filled.Group)
            StatChip("管理员", stats.admins, Icons.Filled.Group)
        }
        Spacer(Modifier.height(6.dp))
        Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()), horizontalArrangement = Arrangement.spacedBy(Space.sm)) {
            StatChip("会话", stats.conversations, null)
            StatChip("消息", stats.messages, null)
            StatChip("文件", stats.files, null)
            StatChip("设备", stats.devices, null)
        }
    }
}

@Composable
private fun StatChip(label: String, value: Int, icon: androidx.compose.ui.graphics.vector.ImageVector?) {
    Surface(
        color = MaterialTheme.colorScheme.secondaryContainer,
        shape = MaterialTheme.shapes.small,
    ) {
        Row(Modifier.padding(horizontal = 10.dp, vertical = 6.dp), verticalAlignment = Alignment.CenterVertically) {
            if (icon != null) {
                Icon(icon, contentDescription = null, modifier = Modifier.size(14.dp))
                Spacer(Modifier.width(Space.xs))
            }
            Text("$label $value", style = MaterialTheme.typography.labelMedium)
        }
    }
}

@Composable
private fun AdminUserRow(u: AdminUser, modifier: Modifier = Modifier, onClick: () -> Unit) {
    ListItem(
        modifier = modifier
            .fillMaxWidth()
            .padding(horizontal = 10.dp, vertical = 3.dp)
            .motionPress(pressedScale = 0.99f)
            .clip(MaterialTheme.shapes.medium)
            .background(MaterialTheme.colorScheme.surfaceContainer)
            .clickable(onClick = onClick),
        colors = androidx.compose.material3.ListItemDefaults.colors(containerColor = androidx.compose.ui.graphics.Color.Transparent),
        leadingContent = { InitialsAvatar(name = u.displayName, size = 40.dp, isBot = u.isBot, online = u.isOnline) },
        headlineContent = {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(u.displayName, fontWeight = FontWeight.Medium, maxLines = 1, overflow = androidx.compose.ui.text.style.TextOverflow.Ellipsis)
                if (u.isAdmin) {
                    Spacer(Modifier.width(6.dp))
                    Surface(color = MaterialTheme.colorScheme.primaryContainer, shape = MaterialTheme.shapes.extraSmall) {
                        Text("管理员", style = MaterialTheme.typography.labelSmall, modifier = Modifier.padding(horizontal = 5.dp, vertical = 1.dp))
                    }
                }
                if (u.isBot) {
                    Spacer(Modifier.width(6.dp))
                    Surface(color = MaterialTheme.colorScheme.tertiaryContainer, shape = MaterialTheme.shapes.extraSmall) {
                        Text("机器人", style = MaterialTheme.typography.labelSmall, modifier = Modifier.padding(horizontal = 5.dp, vertical = 1.dp))
                    }
                }
            }
        },
        supportingContent = {
            Text(
                "@${u.username} · 会话 ${u.conversationCount} · 注册 ${Format.relative(u.createdAt)}",
                style = MaterialTheme.typography.bodySmall,
                maxLines = 1,
            )
        },
        trailingContent = {
            Text(
                if (u.isOnline) stringResource(R.string.status_online) else (u.lastSeen?.let { Format.relative(it) } ?: stringResource(R.string.status_offline)),
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        },
    )
}

@Composable
private fun InviteTab(
    stats: InviteStats,
    invites: List<InviteCode>,
    onGenerate: () -> Unit,
    onCopy: (String) -> Unit,
    onRevoke: (String) -> Unit,
) {
    Column(Modifier.fillMaxSize()) {
        Row(
            Modifier.fillMaxWidth().padding(horizontal = 12.dp, vertical = 8.dp),
            horizontalArrangement = Arrangement.spacedBy(Space.sm),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            StatChip("共", stats.total, null)
            StatChip("未用", stats.unused, null)
            StatChip("已用", stats.used, null)
            Spacer(Modifier.weight(1f))
            Button(onClick = onGenerate) { Text("生成") }
        }
        // 空状态 ↔ 列表 之间淡切。
        FadeSwap(target = invites.isEmpty()) { empty ->
            if (empty) {
                EmptyState(Icons.Filled.CardGiftcard, "还没有邀请码", "点击上方「生成」创建")
            } else {
                LazyColumn(Modifier.fillMaxSize()) {
                    items(invites, key = { it.code }) { inv ->
                        ListItem(
                            modifier = Modifier
                                .animateItem()
                                .fillMaxWidth()
                                .padding(horizontal = 10.dp, vertical = 3.dp)
                                .clip(MaterialTheme.shapes.medium)
                                .background(MaterialTheme.colorScheme.surfaceContainer),
                            colors = androidx.compose.material3.ListItemDefaults.colors(containerColor = androidx.compose.ui.graphics.Color.Transparent),
                            headlineContent = {
                                Text(inv.code, fontFamily = FontFamily.Monospace, fontWeight = FontWeight.Medium)
                            },
                            supportingContent = {
                                Text(
                                    buildString {
                                        append(if (inv.used) "已用" else "未使用")
                                        inv.usedByName?.let { append(" · $it") }
                                        inv.usedAt?.let { append(" · ${Format.relative(it)}") }
                                        append(" · 生成 ${Format.relative(inv.createdAt)}")
                                        inv.createdByName?.let { append(" · by $it") }
                                        inv.note?.takeIf { it.isNotBlank() }?.let { append(" · $it") }
                                    },
                                    style = MaterialTheme.typography.bodySmall,
                                    maxLines = 2,
                                )
                            },
                            trailingContent = {
                                Row {
                                    IconButton(onClick = { onCopy(inv.code) }) {
                                        Icon(Icons.Filled.ContentCopy, stringResource(R.string.action_copy), Modifier.size(18.dp))
                                    }
                                    if (!inv.used) {
                                        IconButton(onClick = { onRevoke(inv.code) }) {
                                            Icon(
                                                Icons.Filled.Delete, "作废", Modifier.size(18.dp),
                                                tint = MaterialTheme.colorScheme.error,
                                            )
                                        }
                                    }
                                }
                            },
                        )
                    }
                }
            }
        }
    }
}

/** 会话列表行：显示成员、消息数、最后活跃时间。 */
@Composable
private fun AdminConversationRow(
    c: com.rtcomm.app.data.AdminConversation,
    modifier: Modifier = Modifier,
    onClick: () -> Unit,
) {
    ListItem(
        modifier = modifier
            .fillMaxWidth()
            .padding(horizontal = 10.dp, vertical = 3.dp)
            .motionPress(pressedScale = 0.99f)
            .clip(MaterialTheme.shapes.medium)
            .background(MaterialTheme.colorScheme.surfaceContainer)
            .clickable(onClick = onClick),
        colors = androidx.compose.material3.ListItemDefaults.colors(containerColor = androidx.compose.ui.graphics.Color.Transparent),
        leadingContent = {
            InitialsAvatar(name = c.title, size = 40.dp, isBot = false, online = null)
        },
        headlineContent = {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(c.title, fontWeight = FontWeight.Medium, maxLines = 1, overflow = androidx.compose.ui.text.style.TextOverflow.Ellipsis)
                Spacer(Modifier.width(6.dp))
                Surface(
                    color = if (c.isGroup) MaterialTheme.colorScheme.tertiaryContainer
                    else MaterialTheme.colorScheme.secondaryContainer,
                    shape = MaterialTheme.shapes.extraSmall,
                ) {
                    Text(
                        if (c.isGroup) "群组" else "单聊",
                        style = MaterialTheme.typography.labelSmall,
                        modifier = Modifier.padding(horizontal = 5.dp, vertical = 1.dp),
                    )
                }
            }
        },
        supportingContent = {
            Text(
                "${c.memberCount} 人 · ${c.messageCount} 条消息" +
                    (c.lastMessageAt?.let { " · " + Format.relative(it) } ?: ""),
                style = MaterialTheme.typography.bodySmall,
                maxLines = 1,
            )
        },
        trailingContent = {
            Text(c.members.take(2).joinToString("、") { it.displayName }, style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant, maxLines = 1)
        },
    )
}

/** 单个账号的管理动作菜单（统一为底部动作面板，与聊天页操作菜单一致）。 */
@Composable
private fun UserActionDialog(
    user: AdminUser,
    onDismiss: () -> Unit,
    onToggleDisabled: () -> Unit,
    onResetPassword: () -> Unit,
    onKick: () -> Unit,
) {
    val status = "@${user.username} · " + (if (user.isBot) "机器人" else "用户") +
        (if (user.isAdmin) " · 管理员" else "") +
        (if (user.isDisabled) " · 已禁用" else "")
    ActionSheet(
        onDismiss = onDismiss,
        title = user.displayName,
        subtitle = status,
        actions = listOf(
            SheetAction(
                icon = if (user.isDisabled) Icons.Filled.Restore else Icons.Filled.Block,
                label = if (user.isDisabled) "恢复账号" else "禁用账号",
                destructive = !user.isDisabled,
                onClick = onToggleDisabled,
            ),
            SheetAction(Icons.Filled.Lock, "重置密码", onClick = onResetPassword),
            SheetAction(Icons.AutoMirrored.Filled.Logout, "踢下线（令其重新登录）", destructive = true, onClick = onKick),
        ),
    )
}

/** 管理员重置密码。 */
@Composable
private fun ResetPasswordDialog(
    user: AdminUser,
    busy: Boolean,
    onDismiss: () -> Unit,
    onConfirm: (String) -> Unit,
) {
    var pwd by remember { mutableStateOf("") }
    AppAlertDialog(
        onDismissRequest = { if (!busy) onDismiss() },
        title = { Text("重置 ${user.displayName} 的密码") },
        text = {
            Column {
                OutlinedTextField(
                    value = pwd,
                    onValueChange = { pwd = it },
                    label = { Text("新密码（≥6 位）") },
                    singleLine = true,
                    visualTransformation = PasswordVisualTransformation(),
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
                    modifier = Modifier.fillMaxWidth(),
                )
                Spacer(Modifier.height(Space.sm))
                Text(
                    "重置后该账号的所有登录状态立即失效，需要用新密码重新登录。",
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        },
        confirmButton = {
            TextButton(onClick = { onConfirm(pwd) }, enabled = !busy && pwd.length >= 6) {
                Text(if (busy) "处理中…" else "重置")
            }
        },
        dismissButton = { TextButton(onClick = onDismiss, enabled = !busy) { Text(stringResource(R.string.action_cancel)) } },
    )
}

/** 查看某个会话的消息（管理员只读）。 */
@Composable
private fun ConversationViewerDialog(
    conversation: com.rtcomm.app.data.AdminConversation,
    onDismiss: () -> Unit,
) {
    var loading by remember { mutableStateOf(true) }
    var err by remember { mutableStateOf<String?>(null) }
    var messages by remember { mutableStateOf<List<com.rtcomm.app.data.Message>>(emptyList()) }
    var expanded by remember { mutableStateOf(true) }

    LaunchedEffect(conversation.id, expanded) {
        if (!expanded) return@LaunchedEffect
        loading = true
        err = null
        val res = withContext(Dispatchers.IO) {
            runCatching { Api.adminConversationMessages(conversation.id) }
        }
        res.onSuccess { messages = it }
        res.onFailure { err = Api.userMessage(it) }
        loading = false
    }

    AppAlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(conversation.title + "（只读）", maxLines = 1) },
        text = {
            Column(Modifier.heightIn(max = 460.dp)) {
                Box(Modifier.fillMaxWidth().height(3.dp)) {
                    if (loading) LinearProgressIndicator(Modifier.fillMaxWidth().height(3.dp))
                }
                err?.let { Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall) }
                // 加载 → 空 → 列表 之间淡切。
                FadeSwap(target = if (loading && messages.isEmpty()) 0 else if (messages.isEmpty()) 1 else 2) { st ->
                    when (st) {
                        0 -> Box(Modifier.fillMaxWidth().padding(vertical = 8.dp))
                        1 -> Text("这个会话还没有消息", style = MaterialTheme.typography.bodySmall)
                        else -> LazyColumn(Modifier.fillMaxWidth()) {
                            items(messages.reversed(), key = { it.id }) { m ->
                                val who = m.sender?.displayName ?: m.senderId.take(6)
                                Text(
                                    "$who： " + when {
                                        m.isDeleted -> "<已撤回>"
                                        m.isFileType -> "[文件] " + (m.file?.fileName ?: "")
                                        else -> Format.mdToPlain(m.content).ifBlank { "[空]" }
                                    },
                                    style = MaterialTheme.typography.bodySmall,
                                    modifier = Modifier.animateItem().fillMaxWidth().padding(vertical = 3.dp),
                                )
                            }
                        }
                    }
                }
                if (messages.size >= 200) {
                    Text(
                        "仅显示最近 200 条",
                        style = MaterialTheme.typography.labelSmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
            }
        },
        confirmButton = { TextButton(onClick = onDismiss) { Text(stringResource(R.string.action_close)) } },
    )
}

/**
 * 全局 AI 提供者默认设置（仅管理员）。
 * API Key 只写不读：服务端仅返回是否已配置，留空表示保持原值。
 */
@OptIn(ExperimentalLayoutApi::class)
@Composable
private fun AiSettingsTab(snackbar: SnackbarHostState) {
    val scope = rememberCoroutineScope()
    var loading by remember { mutableStateOf(true) }
    var err by remember { mutableStateOf<String?>(null) }
    var presets by remember { mutableStateOf<Map<String, com.rtcomm.app.data.ProviderPreset>>(emptyMap()) }
    var saved by remember { mutableStateOf<Map<String, com.rtcomm.app.data.ProviderSettings>>(emptyMap()) }
    var baseUrls by remember { mutableStateOf<Map<String, String>>(emptyMap()) }
    var models by remember { mutableStateOf<Map<String, String>>(emptyMap()) }
    var apiKeys by remember { mutableStateOf<Map<String, String>>(emptyMap()) }
    var busy by remember { mutableStateOf(false) }
    /** 待确认清除 Key 的服务商 id。 */
    var confirmClearKey by remember { mutableStateOf<String?>(null) }

    suspend fun load() {
        loading = true; err = null
        val r = withContext(Dispatchers.IO) { runCatching { Api.providersSettings() } }
        r.onSuccess { res ->
            presets = res.presets
            saved = res.settings
            baseUrls = res.settings.mapValues { it.value.baseUrl.orEmpty() }
            // deepseek 无已保存模型时预填官方可用模型 deepseek-flash。
            models = res.settings.mapValues { (id, s) ->
                s.model.orEmpty().ifBlank {
                    if (id == "deepseek") "deepseek-flash" else res.presets[id]?.model.orEmpty()
                }
            }
        }
        r.onFailure { err = Api.userMessage(it) }
        loading = false
    }
    LaunchedEffect(Unit) { load() }

    val ids = remember(presets, saved) { (presets.keys + saved.keys).toList().sorted() }

    Column(Modifier.fillMaxSize().padding(12.dp)) {
        Text(
            "全局 Key 仅加密存储在服务端、不回显；机器人可在各自配置里单独覆盖。聊天总结优先使用这里配置的 Key。",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        Spacer(Modifier.height(Space.sm))
        if (err != null) ErrorBanner(err!!, onRetry = { scope.launch { load() } })
        if (loading) { LinearProgressIndicator(Modifier.fillMaxWidth()); Spacer(Modifier.height(Space.sm)) }

        LazyColumn(Modifier.weight(1f)) {
            items(ids, key = { it }) { id ->
                val preset = presets[id]
                val s = saved[id]
                Card(Modifier.animateItem().fillMaxWidth().padding(vertical = 5.dp)) {
                    Column(Modifier.padding(12.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text(preset?.label ?: id, fontWeight = FontWeight.Medium, modifier = Modifier.weight(1f))
                            val status = when {
                                s?.hasApiKey == true -> "已配置 Key"
                                preset?.needsApiKey == false -> "无需 Key"
                                else -> "未配置 Key"
                            }
                            AssistChip(onClick = {}, label = { Text(status) })
                        }
                        Spacer(Modifier.height(6.dp))
                        OutlinedTextField(
                            value = baseUrls[id].orEmpty(),
                            onValueChange = { baseUrls = baseUrls + (id to it) },
                            label = { Text("baseUrl") },
                            singleLine = true,
                            supportingText = preset?.baseUrl?.let { url -> { Text("默认 $url") } },
                            modifier = Modifier.fillMaxWidth(),
                        )
                        Spacer(Modifier.height(6.dp))
                        OutlinedTextField(
                            value = models[id].orEmpty(),
                            onValueChange = { models = models + (id to it) },
                            label = { Text("model") },
                            singleLine = true,
                            supportingText = preset?.model?.let { m -> { Text("预设 $m") } },
                            modifier = Modifier.fillMaxWidth(),
                        )
                        // 该提供者的常用模型名，点选即填入。
                        val modelList = preset?.models.orEmpty()
                        if (modelList.isNotEmpty()) {
                            FlowRow(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                                modelList.forEach { m ->
                                    SuggestionChip(
                                        onClick = { models = models + (id to m) },
                                        label = { Text(m) },
                                    )
                                }
                            }
                        }
                        Spacer(Modifier.height(6.dp))
                        OutlinedTextField(
                            value = apiKeys[id].orEmpty(),
                            onValueChange = { apiKeys = apiKeys + (id to it) },
                            label = { Text(if (s?.hasApiKey == true) "API Key（留空保持不变）" else "API Key") },
                            singleLine = true,
                            visualTransformation = PasswordVisualTransformation(),
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
                            modifier = Modifier.fillMaxWidth(),
                        )
                        if (s?.hasApiKey == true) {
                            Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) {
                                TextButton(onClick = { confirmClearKey = id }) {
                                    Text("清除 Key", color = MaterialTheme.colorScheme.error)
                                }
                            }
                        }
                    }
                }
            }
        }

        Spacer(Modifier.height(Space.sm))
        Button(
            enabled = !busy && !loading,
            onClick = {
                busy = true
                scope.launch {
                    val body = mutableMapOf<String, Any?>()
                    for (id in ids) {
                        val part = mutableMapOf<String, Any?>(
                            "baseUrl" to baseUrls[id].orEmpty().trim(),
                            "model" to models[id].orEmpty().trim(),
                        )
                        val key = apiKeys[id].orEmpty()
                        if (key.isNotBlank()) part["apiKey"] = key
                        body[id] = part
                    }
                    val r = withContext(Dispatchers.IO) { runCatching { Api.updateProvidersSettings(body) } }
                    busy = false
                    r.onSuccess { apiKeys = emptyMap(); snackbar.showSnackbar("全局 AI 设置已保存"); load() }
                        .onFailure { err = Api.userMessage(it); snackbar.showSnackbar(Api.userMessage(it)) }
                }
            },
            modifier = Modifier.fillMaxWidth(),
        ) { Text(if (busy) "保存中…" else "保存全局设置") }

        confirmClearKey?.let { id ->
            ConfirmDialog(
                title = "清除 API Key",
                message = "将清除「${id}」在服务端保存的全局 API Key，使用该 Key 的机器人/总结会立即失效。",
                confirmText = "清除",
                onConfirm = {
                    scope.launch {
                        val r = withContext(Dispatchers.IO) {
                            runCatching { Api.updateProvidersSettings(mapOf(id to mapOf("apiKey" to ""))) }
                        }
                        r.onSuccess { snackbar.showSnackbar("已清除 $id 的 Key"); load() }
                            .onFailure { snackbar.showSnackbar(Api.userMessage(it)) }
                    }
                },
                onDismiss = { confirmClearKey = null },
            )
        }
    }
}

/**
 * 额度兑换码管理（仅管理员）：自定义额度与有效期，生成/复制/作废。
 */
@OptIn(ExperimentalMaterial3Api::class, ExperimentalLayoutApi::class)
@Composable
private fun RedeemCodesTab(
    snackbar: SnackbarHostState,
    clipboard: androidx.compose.ui.platform.ClipboardManager,
) {
    val scope = rememberCoroutineScope()
    var tokens by remember { mutableStateOf("10000") }
    var count by remember { mutableStateOf("1") }
    var days by remember { mutableStateOf("0") }
    var note by remember { mutableStateOf("") }
    var busy by remember { mutableStateOf(false) }
    var err by remember { mutableStateOf<String?>(null) }
    var codes by remember { mutableStateOf<List<com.rtcomm.app.data.RedeemCode>>(emptyList()) }
    var loading by remember { mutableStateOf(true) }
    var lastCreated by rememberSaveable(stateSaver = StringListSaver) { mutableStateOf<List<String>>(emptyList()) }
    /** 待确认作废的兑换码。 */
    var confirmRevoke by remember { mutableStateOf<String?>(null) }

    suspend fun load() {
        loading = true
        val r = withContext(Dispatchers.IO) { runCatching { Api.redeemCodes() } }
        r.onSuccess { codes = it }
        r.onFailure { err = Api.userMessage(it) }
        loading = false
    }
    LaunchedEffect(Unit) { load() }

    Column(Modifier.fillMaxSize().padding(12.dp)) {
        Text("发放额度兑换码", style = MaterialTheme.typography.titleSmall)
        Spacer(Modifier.height(Space.sm))
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(Space.sm)) {
            OutlinedTextField(
                tokens, { tokens = it }, label = { Text("额度(tokens)") }, singleLine = true,
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number), modifier = Modifier.weight(1f),
            )
            OutlinedTextField(
                count, { count = it }, label = { Text("数量") }, singleLine = true,
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number), modifier = Modifier.width(96.dp),
            )
        }
        Spacer(Modifier.height(6.dp))
        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(Space.sm)) {
            OutlinedTextField(
                days, { days = it }, label = { Text("有效期(天, 0=永久)") }, singleLine = true,
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number), modifier = Modifier.weight(1f),
            )
            OutlinedTextField(note, { note = it }, label = { Text("备注(可选)") }, singleLine = true, modifier = Modifier.weight(1f))
        }
        Spacer(Modifier.height(Space.sm))
        Button(
            enabled = !busy,
            onClick = {
                val t = tokens.trim().toIntOrNull() ?: 0
                val c = count.trim().toIntOrNull() ?: 1
                val d = days.trim().toIntOrNull() ?: 0
                if (t <= 0) { err = "额度必须为正整数"; return@Button }
                busy = true; err = null
                scope.launch {
                    val expiresAt = if (d > 0) {
                        java.time.Instant.now().plus(d.toLong(), java.time.temporal.ChronoUnit.DAYS).toString()
                    } else null
                    val r = withContext(Dispatchers.IO) {
                        runCatching { Api.createRedeemCodes(t, c, expiresAt, note.ifBlank { null }) }
                    }
                    busy = false
                    r.onSuccess { res ->
                        lastCreated = res.codes
                        snackbar.showSnackbar("已生成 ${res.codes.size} 个兑换码")
                        load()
                    }
                    r.onFailure { err = Api.userMessage(it) }
                }
            },
            modifier = Modifier.fillMaxWidth(),
        ) { Text(if (busy) "生成中…" else "生成兑换码") }
        err?.let { Spacer(Modifier.height(6.dp)); Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodySmall) }

        Reveal(lastCreated.isNotEmpty()) {
            if (lastCreated.isNotEmpty()) {
                Spacer(Modifier.height(Space.sm))
                Card(Modifier.fillMaxWidth()) {
                    Column(Modifier.padding(12.dp)) {
                        Text("刚刚生成", style = MaterialTheme.typography.labelMedium)
                        lastCreated.forEach { code ->
                            Row(Modifier.fillMaxWidth(), verticalAlignment = Alignment.CenterVertically) {
                                Text(code, fontFamily = FontFamily.Monospace, modifier = Modifier.weight(1f))
                                IconButton(onClick = {
                                    clipboard.setText(AnnotatedString(code))
                                    scope.launch { snackbar.showSnackbar("已复制") }
                                }) { Icon(Icons.Filled.ContentCopy, contentDescription = stringResource(R.string.action_copy)) }
                            }
                        }
                    }
                }
            }
        }

        Spacer(Modifier.height(10.dp))
        Text("历史兑换码", style = MaterialTheme.typography.titleSmall)
        if (loading) LinearProgressIndicator(Modifier.fillMaxWidth())
        LazyColumn(Modifier.weight(1f)) {
            items(codes, key = { it.code }) { c ->
                Card(Modifier.animateItem().fillMaxWidth().padding(vertical = 4.dp)) {
                    Column(Modifier.padding(10.dp)) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Text(c.code, fontFamily = FontFamily.Monospace, modifier = Modifier.weight(1f))
                            IconButton(onClick = {
                                clipboard.setText(AnnotatedString(c.code))
                                scope.launch { snackbar.showSnackbar("已复制") }
                            }) { Icon(Icons.Filled.ContentCopy, contentDescription = stringResource(R.string.action_copy)) }
                        }
                        Text(
                            buildString {
                                append("${c.tokens} tokens · ")
                                append(if (c.expiresAt != null) "有效期至 ${c.expiresAt}" else "永久")
                                append(if (c.usedBy != null) " · 已使用" else " · 未使用")
                            },
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                        c.note?.takeIf { it.isNotBlank() }?.let { Text(it, style = MaterialTheme.typography.labelSmall) }
                        if (c.usedBy == null) {
                            TextButton(onClick = { confirmRevoke = c.code }) {
                                Text("作废", color = MaterialTheme.colorScheme.error)
                            }
                        }
                    }
                }
            }
        }

        confirmRevoke?.let { code ->
            ConfirmDialog(
                title = "作废兑换码",
                message = "作废后「$code」将无法再被兑换，此操作不可撤销。",
                confirmText = "作废",
                onConfirm = {
                    scope.launch {
                        val r = withContext(Dispatchers.IO) { runCatching { Api.revokeRedeemCode(code) } }
                        r.onSuccess { snackbar.showSnackbar("已作废"); load() }
                            .onFailure { snackbar.showSnackbar(Api.userMessage(it)) }
                    }
                },
                onDismiss = { confirmRevoke = null },
            )
        }
    }
}
